name: RapiDAST Scan

on:
  workflow_dispatch:

jobs:
  dast:
    runs-on: ubuntu-latest

    container:
      image: quay.io/redhatproductsecurity/rapiddast:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run RapiDAST Scan (no docker)
        run: |
          rapiddast scan \
            -c rapiddast/config.yaml \
            --output rapiddast/report

      - name: Upload DAST Report
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: rapiddast/report/
